version: '2.29'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    environment:
      - DB_HOST: localhost
      - DB_NAME: deploy
      - DB_USER: root
      - DB_PASSWORD: password
      - DB_PORT: 3306
      - DB_NAME: deploy
    ports:
      - 45000:3500
  
  ui:
    build: 
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
    ports:
      - 3001:3000
