version: '2.29'

services:
  nginx:
    image: nginx:latest
    container_name: deploy_nginx
    ports:
      - "3501:80"
    volumes:
      - ./nginx/.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - ui

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: 10.30.10.12
      DB_NAME: deploy
      DB_USER: root
      DB_PASSWORD: password
      DB_PORT: 3306
    ports:
      - 4500:3500

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 3001:80
